"""The controlled-intervention data model: state + render → one observation.

The scientific unit here is the *observation*: a state snapshot paired with a
render of that exact state. Two observations plus the *known* semantic change
between them form a controlled A/B — the difference that lets the analyzer say
"this state delta produced this audio delta", rather than presenting two
unrelated sessions and hoping the reader connects them.

These models are deliberately DAW-agnostic. The semantic ``Intervention``
("add a post-fader effect send from the vocal to a shared reverb return") is
the same sentence in every DAW; each DAW's *native* realization of it rides in
``native_implementations`` keyed by dialect. Everything is pydantic so an
experiment round-trips through ``intervention.json`` losslessly and an
``AudioDescriptorSet`` embeds directly.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

from session_explorer.core.models import AudioDescriptorSet

# A small, interpretable vocabulary for "what knob did this change move?". It is
# optional on an Intervention — a routing change like an added send has a
# SEND_LEVEL character; a plugin-parameter tweak names its own role.
SemanticParameterRole = Literal[
    "GAIN",
    "PAN",
    "SEND_LEVEL",
    "FEEDBACK",
    "WET_DRY",
    "CUTOFF",
    "RESONANCE",
    "THRESHOLD",
    "RATIO",
    "TEMPO",
]


class Render(BaseModel):
    """One audio render of one exact session state.

    ``synthetic`` is load-bearing honesty: a render generated by a fixture
    pipeline (rather than printed from a human-made session) says so, exactly
    like the Logic synthetic demo. ``descriptor`` carries the acoustic reading
    of the file; the file itself is not shipped (descriptors travel, WAVs do
    not).
    """

    id: str
    file_name: str
    synthetic: bool = False
    sample_rate: Optional[int] = None
    channels: Optional[int] = None
    n_samples: Optional[int] = None
    descriptor: Optional[AudioDescriptorSet] = None
    notes: Optional[str] = None


class Observation(BaseModel):
    """One row of the research corpus: a snapshot, optionally paired with a render.

    Per the master prompt's observation unit — a state snapshot plus the render
    of that state. ``render_id`` references a :class:`Render`; ``fixture_id``
    names the bundle on disk; ``intervention_id`` is set on the *after* side of
    a controlled pair (the baseline "before" leaves it ``None``).
    """

    id: str
    snapshot_id: str
    render_id: Optional[str] = None
    fixture_id: Optional[str] = None
    intervention_id: Optional[str] = None


class Intervention(BaseModel):
    """One known, controlled change between two observations.

    ``description`` is the semantic, DAW-agnostic sentence — the thing a
    producer would say. ``native_implementations`` maps a dialect to how *that*
    DAW spells it (``{"cubase": "<Send destination=ch-fx1 type=post> on the vox
    channel"}``). ``before`` / ``after`` are the two observations the change
    sits between.
    """

    id: str
    description: str
    semantic_role: Optional[SemanticParameterRole] = None
    native_implementations: dict[str, str] = Field(default_factory=dict)
    before: Observation
    after: Observation


class DeltaRecord(BaseModel):
    """A compact record of one added / removed / changed graph element."""

    id: str
    type: str
    label: str


class StateDelta(BaseModel):
    """The structural difference between two canonical snapshots.

    Entities are compared by id; relationships by ``(rel_type, source,
    target)``. Everything is a compact :class:`DeltaRecord` so the delta is a
    presentable object, not two raw snapshots the reader must diff by eye.
    ``added_sends`` is a convenience view onto the ``CHANNEL_SENDS_TO`` edges in
    ``added_relationships`` — the routing change this experiment is *about*.
    """

    added_entities: list[DeltaRecord] = Field(default_factory=list)
    removed_entities: list[DeltaRecord] = Field(default_factory=list)
    added_relationships: list[DeltaRecord] = Field(default_factory=list)
    removed_relationships: list[DeltaRecord] = Field(default_factory=list)
    changed: list[DeltaRecord] = Field(default_factory=list)
    added_sends: list[DeltaRecord] = Field(default_factory=list)


class SignalFlowChange(BaseModel):
    """A human-readable trace of how the added routing changes the signal path.

    ``summary`` is one plain sentence; ``path`` is the left-to-right chain the
    new signal travels (source channel → send target → its processor(s) → its
    output), so the sentence and the diagram cannot disagree.
    """

    summary: str
    path: list[str] = Field(default_factory=list)


class AcousticMetric(BaseModel):
    """One before/after acoustic measurement and its signed delta."""

    name: str
    before: Optional[float] = None
    after: Optional[float] = None
    delta: Optional[float] = None
    unit: str = ""
    direction: Optional[str] = None


class AcousticDelta(BaseModel):
    """The measured change in the render's sound, metric by metric."""

    metrics: list[AcousticMetric] = Field(default_factory=list)
    summary: str = ""
    available: bool = True
    unavailable_reason: Optional[str] = None


class InterventionComparison(BaseModel):
    """The whole state→audio chain for one controlled intervention.

    One object carries the three beats of the demonstration: what changed in
    the *state* (:class:`StateDelta`), *why* the sound changes
    (:class:`SignalFlowChange`), and *how much* it changed
    (:class:`AcousticDelta`).
    """

    intervention: Intervention
    state_delta: StateDelta
    signal_flow: SignalFlowChange
    acoustic_delta: AcousticDelta
