"""JSON export: the unified/native research bundle and its building blocks.

The bundle format makes observed, inferred, annotated and hidden information
explicit. Losslessness is honoured by the two-view design:

- ``unified``: the canonical session dump plus graph, descriptors,
  recommendations, hidden-state markers and a PROV-O-grounded provenance
  block.
- ``native``: the originating dialect's verbatim native model — nothing a DAW
  exposes can be dropped by accident.

The export schema is intentionally simple and self-describing so it can be
shown in the README and reused as a unit of analysis in future research
(e.g. comparing many sessions). All payloads are plain JSON-serialisable
dicts.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable, List, Optional

import networkx as nx

from .models import (
    CANONICAL_SCHEMA_VERSION,
    AudioDescriptorSet,
    CanonicalSession,
    Recommendation,
    to_dict,
)
from .utils import slugify

VIEWS = ("unified", "native", "both")

# ---------------------------------------------------------------------------
# W3C PROV-O mapping. The session graph is a provenance graph in disguise:
# observed artifacts are primary-source entities, annotations are entities
# attributed to the producer, derived analyses were generated by tool
# activities, and hidden-state markers are an honest extension class
# (sse:HiddenState) marking state PROV cannot attest because no evidence
# reaches it. Edge types map onto PROV relations as below.
# ---------------------------------------------------------------------------

PROV_EDGE_RELATIONS = {
    # canonical structural edges
    "has_track": "prov:hadMember",
    "has_scene": "prov:hadMember",
    "has_clip": "prov:hadMember",
    "has_processor": "prov:hadMember",
    "has_route": "prov:hadMember",
    "references_audio": "prov:hadMember",
    "uses_audio_file": "prov:hadMember",
    "sends_to": "prov:wasInfluencedBy",
    "routes_to": "prov:wasInfluencedBy",
    "has_unresolved_route": "prov:wasInfluencedBy",
    # evidence edges (Logic lineage)
    "contains_audio": "prov:hadMember",
    "infers_track": "prov:wasDerivedFrom",
    "has_descriptor": "prov:wasDerivedFrom",
    "linked_to_midi": "prov:wasDerivedFrom",
    "linked_to_score_part": "prov:wasDerivedFrom",
    "annotated_by": "prov:wasAttributedTo",
    "mentions_plugin": "prov:hadMember",
    "mentions_send": "prov:hadMember",
    "mentions_bus": "prov:hadMember",
    "compared_to_reference": "prov:wasInfluencedBy",
    "part_of_reconciliation": "prov:wasDerivedFrom",
    "part_of_comparison": "prov:wasDerivedFrom",
    "has_hidden_state": "sse:hasHiddenState",
    "supports_recommendation": "prov:wasDerivedFrom",
}

PROV_OBSERVABILITY_TYPES = {
    "observed": "prov:PrimarySource",
    "inferred": "sse:InferredEntity",
    "annotation": "sse:UserAssertion",
    "derived": "prov:Entity",
    "hidden": "sse:HiddenState",
}

_PROV_PREFIX = {
    "prov": "http://www.w3.org/ns/prov#",
    "sse": "https://github.com/ColonelKernel/SessionStateExplorer#",
}


# ---------------------------------------------------------------------------
# Building blocks
# ---------------------------------------------------------------------------


def session_json(session: CanonicalSession) -> dict:
    """The canonical session as a plain JSON-serialisable dict."""

    return to_dict(session)


def graph_to_dict(graph: nx.DiGraph) -> dict:
    """Serialise a graph to plain dicts suitable for JSON export or visualization."""

    nodes = []
    for node_id, data in graph.nodes(data=True):
        node = {"id": node_id}
        node.update({k: v for k, v in data.items() if k != "id"})
        nodes.append(node)

    edges = []
    for source, target, data in graph.edges(data=True):
        edge = {"source": source, "target": target}
        edge.update(data)
        edges.append(edge)

    return {"nodes": nodes, "edges": edges, "metadata": dict(graph.graph)}


def graph_export(graph: nx.DiGraph) -> dict:
    """Graph-only export (nodes/edges/metadata)."""

    return {"schema_version": CANONICAL_SCHEMA_VERSION, "graph": graph_to_dict(graph)}


def descriptors_export(descriptors: List[AudioDescriptorSet]) -> dict:
    """Descriptors-only export."""

    return {
        "schema_version": CANONICAL_SCHEMA_VERSION,
        "descriptors": to_dict(list(descriptors)),
    }


def recommendations_export(recommendations: List[Recommendation]) -> dict:
    """Recommendations-only export."""

    return {
        "schema_version": CANONICAL_SCHEMA_VERSION,
        "recommendations": to_dict(list(recommendations)),
    }


def hidden_state_json(session: CanonicalSession) -> list:
    """The session's hidden-state markers as plain dicts."""

    return to_dict(session.hidden_state_markers)


# ---------------------------------------------------------------------------
# PROV-O view
# ---------------------------------------------------------------------------


def _session_prov_nodes(session: CanonicalSession) -> List[dict]:
    """Flatten the canonical session into provenance-annotated node records.

    Used when no graph is supplied: every canonical entity becomes a
    prov:Entity carrying its observability class and source artifact.
    """

    nodes: List[dict] = [
        {
            "id": "session",
            "label": session.name,
            "type": "session",
            "observability": "observed",
            "source_artifact": session.source_file,
        }
    ]

    def add(entity_id: str, label: str, node_type: str, provenance=None,
            observability: Optional[str] = None) -> None:
        nodes.append(
            {
                "id": entity_id,
                "label": label,
                "type": node_type,
                "observability": observability
                or (provenance.observability if provenance else "derived"),
                "source_artifact": provenance.source_artifact if provenance else None,
            }
        )

    for track in session.tracks:
        add(track.id, track.name or track.id, "track", track.provenance)
        for clip in track.clips:
            add(clip.id, clip.name or clip.id, "clip", clip.provenance)
        for proc in track.processors:
            add(proc.id, proc.name, "processor", proc.provenance)
    for scene in session.scenes:
        add(scene.id, scene.name or scene.id, "scene", scene.provenance)
    for route in session.routes:
        label = f"{route.source_name or route.source_track_id} → " \
                f"{route.target_name or route.target_track_id}"
        add(route.id, label, "route", route.provenance)
    for index, descriptor in enumerate(session.descriptors):
        add(descriptor.id or f"descriptor-{index + 1}", descriptor.file_name or "descriptors",
            "descriptor_set", None, observability="derived")
    for marker in session.hidden_state_markers:
        add(marker.id, marker.hidden_state_type, "hidden_state_marker", None,
            observability="hidden")
    for rec in session.recommendations:
        add(rec.id, rec.title, "recommendation", None, observability="derived")
    if session.evidence:
        for audio in session.evidence.audio_files:
            add(audio.id, audio.file_name, "audio_evidence", None, observability="observed")
        for note in session.evidence.channel_strip_notes:
            add(note.id, note.track_name, "channel_strip_note", None, observability="annotation")
    return nodes


def _graph_prov_nodes(graph: nx.DiGraph) -> List[dict]:
    return [
        {
            "id": node_id,
            "label": data.get("label", node_id),
            "type": data.get("type", "unknown"),
            "observability": data.get("observability", "derived"),
            "source_artifact": data.get("source_artifact"),
        }
        for node_id, data in graph.nodes(data=True)
    ]


def prov_json(session: CanonicalSession, graph: Optional[nx.DiGraph] = None) -> dict:
    """A PROV-O-grounded JSON view of the session.

    Grounds the graph schema in W3C PROV-O *vocabulary* (in a bespoke JSON
    layout — this is not the W3C PROV-JSON serialization): entities carry
    their observability class as a type, derivations follow the edge mapping
    in ``PROV_EDGE_RELATIONS``, user annotations are attributed to the
    producer agent, and inferred/derived entities are attributed to the tool
    agent. Observed entities are additionally attributed to the evidence
    artifact agent they were parsed from (``sse:artifact:rpp_file`` and so
    on), so the unified view stays honest about *which* artifact attests each
    fact. Hidden-state markers use the honest extension class
    ``sse:HiddenState`` — provenance for what the evidence cannot attest.

    When ``graph`` is provided its nodes/edges drive the view; otherwise the
    canonical session's entities are flattened directly.
    """

    nodes: Iterable[dict] = _graph_prov_nodes(graph) if graph is not None else _session_prov_nodes(session)

    entities: dict = {}
    attributions: List[dict] = []
    agents: dict = {
        "sse:producer": {
            "prov:type": "prov:Person",
            "prov:label": "Producer (user-provided annotations)",
        },
        "sse:explorer": {
            "prov:type": "prov:SoftwareAgent",
            "prov:label": "Session State Explorer",
        },
    }

    for node in nodes:
        observability = node.get("observability") or "derived"
        entities[f"sse:{node['id']}"] = {
            "prov:label": node.get("label", node["id"]),
            "prov:type": PROV_OBSERVABILITY_TYPES.get(observability, "prov:Entity"),
            "sse:node_type": node["type"],
            "sse:observability": observability,
        }
        # Inferred/derived entities (and hidden-state markers) are products of
        # this tool; annotations are attributed to the producer; observed
        # entities to the evidence artifact that attests them.
        if observability in ("inferred", "derived", "hidden"):
            attributions.append({
                "prov:entity": f"sse:{node['id']}",
                "prov:agent": "sse:explorer",
                "sse:basis": "generated_by_tool",
            })
        elif observability == "annotation":
            attributions.append({
                "prov:entity": f"sse:{node['id']}",
                "prov:agent": "sse:producer",
                "sse:basis": "user_assertion",
            })
        elif observability == "observed" and node.get("source_artifact"):
            agent_id = f"sse:artifact:{node['source_artifact']}"
            agents.setdefault(agent_id, {
                "prov:type": "sse:EvidenceArtifact",
                "prov:label": f"Evidence artifact ({node['source_artifact']})",
            })
            attributions.append({
                "prov:entity": f"sse:{node['id']}",
                "prov:agent": agent_id,
                "sse:basis": "observed_in_artifact",
            })

    relations: dict = {}
    if graph is not None:
        for source, target, data in graph.edges(data=True):
            edge_type = data.get("type", "")
            relation = PROV_EDGE_RELATIONS.get(edge_type, "prov:wasInfluencedBy")
            if relation == "prov:wasAttributedTo":
                attributions.append({
                    "prov:entity": f"sse:{target}",
                    "prov:agent": "sse:producer",
                    "sse:edge_type": edge_type,
                })
            else:
                relations.setdefault(relation, []).append({
                    "prov:entity": f"sse:{target}",
                    "prov:source": f"sse:{source}",
                    "sse:edge_type": edge_type,
                })

    return {
        "prefix": dict(_PROV_PREFIX),
        "agent": agents,
        "entity": entities,
        "wasAttributedTo": attributions,
        "relations": relations,
        "note": (
            "sse:HiddenState entities record session state that no available "
            "evidence attests; they are deliberate extensions, not PROV-O terms."
        ),
    }


# ---------------------------------------------------------------------------
# The two-view bundle
# ---------------------------------------------------------------------------


def _unified_bundle(session: CanonicalSession, graph: Optional[nx.DiGraph]) -> dict:
    warnings = list(session.warnings)
    for descriptor in session.descriptors:
        warnings.extend(descriptor.warnings)

    return {
        "schema_version": CANONICAL_SCHEMA_VERSION,
        "session": to_dict(session),
        "graph": graph_to_dict(graph) if graph is not None else None,
        "descriptors": to_dict(session.descriptors),
        "hidden_state_markers": to_dict(session.hidden_state_markers),
        "recommendations": to_dict(session.recommendations),
        "prov": prov_json(session, graph),
        "warnings": warnings,
        "export_metadata": {
            "dialect": session.dialect,
            "view": "unified",
            "graph_included": graph is not None,
            "native_payload_available": session.native is not None,
        },
    }


def _native_bundle(session: CanonicalSession) -> dict:
    if session.native is None:
        raise ValueError(
            "This session carries no native payload: the driver did not attach "
            "session.native, so a native-view export is impossible. "
            "Use view='unified' instead."
        )
    return {
        "dialect": session.native.dialect,
        "model_name": session.native.model_name,
        "model": to_dict(session.native.model),
    }


def build_bundle(
    session: CanonicalSession,
    graph: Optional[nx.DiGraph] = None,
    view: str = "unified",
) -> dict:
    """Assemble the export bundle in the requested view.

    - ``"unified"``: canonical session dump + graph + descriptors +
      recommendations + hidden-state markers + PROV-O block.
    - ``"native"``: the originating dialect's verbatim native model
      (raises ``ValueError`` when ``session.native`` is absent).
    - ``"both"``: ``{"unified": ..., "native": ...}``.
    """

    if view == "unified":
        return _unified_bundle(session, graph)
    if view == "native":
        return _native_bundle(session)
    if view == "both":
        return {
            "unified": _unified_bundle(session, graph),
            "native": _native_bundle(session),
        }
    raise ValueError(f"Unknown export view {view!r}; expected one of {VIEWS}.")


# ---------------------------------------------------------------------------
# Serialisation + file writing
# ---------------------------------------------------------------------------


def _json_default(obj: Any) -> Any:
    """Fallback serialiser for numpy scalars and other stragglers."""

    # numpy scalar types expose .item(); avoid importing numpy here.
    if hasattr(obj, "item") and callable(obj.item):
        try:
            return obj.item()
        except Exception:  # pragma: no cover - defensive
            pass
    if hasattr(obj, "tolist") and callable(obj.tolist):
        return obj.tolist()
    if isinstance(obj, (set, frozenset)):
        return list(obj)
    return str(obj)


def to_json_str(payload: dict, indent: int = 2) -> str:
    """Pretty JSON string with safe defaults for numpy / non-serialisable values."""

    return json.dumps(payload, indent=indent, default=_json_default)


def to_json_bytes(payload: dict, indent: int = 2) -> bytes:
    """UTF-8 encoded JSON, convenient for Streamlit download buttons."""

    return to_json_str(payload, indent=indent).encode("utf-8")


def write_bundle(
    session: CanonicalSession,
    output_dir: Path,
    *,
    graph: Optional[nx.DiGraph] = None,
    view: str = "unified",
    filename: Optional[str] = None,
) -> Path:
    """Build the bundle and write it to ``output_dir`` as pretty-printed JSON.

    Returns the written path. The default filename embeds the session name
    and the view (``my-session_unified_bundle.json``).
    """

    bundle = build_bundle(session, graph=graph, view=view)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    if filename is None:
        filename = f"{slugify(session.name, 'session')}_{view}_bundle.json"
    output_path = output_dir / filename
    output_path.write_text(to_json_str(bundle), encoding="utf-8")
    return output_path
