"""X06 grouping-depth fixture: loads, validates, and carries every P6 case.

The fixture is generated by the real ``flatten_session`` pipeline
(``inputs/make_inputs.py``); this test is the frozen-bundle contract check that
it still exhibits grouping honesty, VCA control, channel'd sends, chain-scoped
processing order, and a detectable routing cycle.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from session_explorer.graph_layers import build_graph, decompose_group, detect_cycles
from session_explorer.loaders.bundle import load_bundle

X06 = (
    Path(__file__).resolve().parents[2]
    / "fixtures"
    / "cross-daw"
    / "X06_grouping_depth"
    / "bundles"
    / "synthetic"
)


@pytest.fixture(scope="module")
def bundle():
    if not (X06 / "canonical.snapshot.json").exists():
        pytest.skip("X06 fixture not generated")
    return load_bundle(X06)


def _rels(snapshot, rel_type):
    return [(r.source, r.target) for r in snapshot.relationships_of_type(rel_type)]


def test_x06_loads_and_validates(bundle):
    assert bundle.validation.valid
    assert bundle.validation.errors == []
    assert bundle.snapshot.source.daw == "synthetic"


def test_x06_grouping_honesty(bundle):
    """Org folder is CONTAINS-only; the drum bus additionally SUMS_TO."""
    snapshot = bundle.snapshot
    sums = _rels(snapshot, "SUMS_TO")
    # Only the drum bus sums (2 children); the org folder does not.
    assert ("synthetic:track-kick:channel", "synthetic:bus-drum:channel") in sums
    assert ("synthetic:track-snare:channel", "synthetic:bus-drum:channel") in sums
    assert len(sums) == 2
    # But both folders contain their children.
    group_contains = [
        (r.source, r.target)
        for r in snapshot.relationships_of_type("CONTAINS")
        if r.properties.get("kind") == "group_member"
    ]
    assert ("synthetic:folder-org", "synthetic:track-perc") in group_contains
    assert ("synthetic:bus-drum", "synthetic:track-kick") in group_contains
    # The org folder decomposes to containment alone.
    assert not decompose_group(snapshot, "synthetic:folder-org").is_multi_concept()


def test_x06_vca_controls(bundle):
    controls = bundle.snapshot.relationships_of_type("CONTROLS")
    assert {(r.source, r.target) for r in controls} == {
        ("synthetic:vca-drums:channel", "synthetic:track-kick:channel"),
        ("synthetic:vca-drums:channel", "synthetic:track-snare:channel"),
    }
    assert all(r.properties["kind"] == "vca_or_edit_group" for r in controls)


def test_x06_channelled_sends(bundle):
    sends = bundle.snapshot.relationships_of_type("CHANNEL_SENDS_TO")
    by_layout = {
        r.properties.get("channel_layout"): r.properties
        for r in sends
        if "channel_layout" in r.properties
    }
    assert by_layout["stereo"]["source_channels"] == [0, 1]
    assert by_layout["stereo"]["channel_count"] == 2
    assert by_layout["mono"]["source_channels"] == [2]
    assert by_layout["mono"]["channel_count"] == 1
    # The feedback sends are stereo-implicit: no channel keys.
    feedback = [
        r for r in sends
        if r.source == "synthetic:track-fb-a:channel"
    ]
    assert feedback and "channel_count" not in feedback[0].properties


def test_x06_processing_precedes_chain_scoped(bundle):
    precedes = {
        (r.source, r.target): r.properties.get("chain")
        for r in bundle.snapshot.relationships_of_type("PRECEDES")
    }
    assert precedes == {
        ("synthetic:proc-eq", "synthetic:proc-delay"): "main",
        ("synthetic:proc-sat", "synthetic:proc-chorus"): "parallel",
    }


def test_x06_has_detectable_cycle(bundle):
    graph = build_graph(bundle.snapshot, layer="all")
    report = detect_cycles(graph)
    assert report.has_cycles
    assert report.cycle_nodes == frozenset(
        {"synthetic:track-fb-a:channel", "synthetic:track-fb-b:channel"}
    )
