"""The variants analyzer (P8): grouping, lineage graph, and version diffing.

Runs against the synthetic ``demo_song`` family under ``fixtures/variants/``
(generated by ``inputs/make_inputs.py`` through the real ``flatten_session`` +
``validate_snapshot`` pipeline, so the frozen bundles cannot drift). The family
is one root (v1), a linear child (v2) and its grandchild (v3), plus an
alternative sibling of v2 (v2_alpha):

* ``build_variant_set`` groups v1/v2/v3 into one family, ordered v1 < v2 < v3;
* ``build_variant_graph`` draws DERIVED_FROM down the chain, SHARES_SOURCE_WITH
  across the shared audio asset, and ALTERNATIVE_OF between the siblings;
* ``variant_diff`` reports the +1 track (v1→v2) and the +1 send and the EQ
  parameter change (v2→v3).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from session_explorer.loaders.bundle import load_bundle
from session_explorer.variants import (
    VariantMember,
    VariantSet,
    build_variant_graph,
    build_variant_set,
    variant_diff,
)

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "variants"
MEMBER_NAMES = ("v1", "v2", "v3", "v2_alpha")


def _require_fixtures() -> None:
    for name in MEMBER_NAMES:
        if not (FIXTURES / name / "canonical.snapshot.json").exists():
            pytest.skip(f"variants fixture {name!r} not generated")


@pytest.fixture(scope="module")
def bundles():
    _require_fixtures()
    return {name: load_bundle(FIXTURES / name) for name in MEMBER_NAMES}


def _variant_node(graph, snapshot_ordinal: int):
    """The composed graph's VARIANT node for the member at position ``i``."""
    for node, data in graph.nodes(data=True):
        if data.get("type") == "VARIANT" and data.get("snapshot_ordinal") == snapshot_ordinal:
            return node
    raise AssertionError(f"no VARIANT node at snapshot_ordinal {snapshot_ordinal}")


def _edges_of_type(graph, rel_type: str):
    return [(u, v) for u, v, d in graph.edges(data=True) if d.get("type") == rel_type]


# ---------------------------------------------------------------------------
# Fixtures validate
# ---------------------------------------------------------------------------


def test_all_fixtures_validate(bundles):
    """Every member bundle re-validates on load under the contract."""
    for name, bundle in bundles.items():
        assert bundle.validation.valid, name
        assert bundle.validation.errors == [], name
        assert bundle.snapshot.entities_of_type("VARIANT"), name


# ---------------------------------------------------------------------------
# build_variant_set
# ---------------------------------------------------------------------------


def test_build_variant_set_groups_one_family_ordered(bundles):
    """v1/v2/v3 group into one family, ordered v1 < v2 < v3 by ordinal."""
    sets = build_variant_set([bundles["v1"], bundles["v2"], bundles["v3"]])
    assert len(sets) == 1
    variant_set = sets[0]
    assert isinstance(variant_set, VariantSet)
    assert variant_set.family == "demo_song"
    assert variant_set.labels() == ["v1", "v2", "v3"]
    assert [m.ordinal for m in variant_set.members] == [0, 1, 2]
    assert all(isinstance(m, VariantMember) for m in variant_set.members)


def test_build_variant_set_ordinals_from_derived_from_chain(bundles):
    """The ordinal is recovered from the derived-from chain, siblings tie."""
    sets = build_variant_set(list(bundles.values()))
    assert len(sets) == 1
    by_label = {m.label: m for m in sets[0].members}
    assert by_label["v1"].ordinal == 0
    assert by_label["v2"].ordinal == 1
    assert by_label["v2_alpha"].ordinal == 1  # sibling of v2
    assert by_label["v3"].ordinal == 2
    # v2 sorts before its sibling (stable tie-break on snapshot id).
    labels = sets[0].labels()
    assert labels.index("v2") < labels.index("v2_alpha")


def test_build_variant_set_skips_bundles_without_variant(bundles):
    """A bundle carrying no VARIANT entity is not part of any set."""
    from session_explorer.loaders.bundle import load_bundle as _load

    x06 = (
        Path(__file__).resolve().parents[2]
        / "fixtures"
        / "cross-daw"
        / "X06_grouping_depth"
        / "bundles"
        / "synthetic"
    )
    extra = []
    if (x06 / "canonical.snapshot.json").exists():
        extra = [_load(x06)]  # a real bundle with no VARIANT entity
    sets = build_variant_set([bundles["v1"], bundles["v2"], *extra])
    # Only the demo_song family is returned; the VARIANT-less bundle is dropped.
    assert [s.family for s in sets] == ["demo_song"]
    assert {m.label for m in sets[0].members} == {"v1", "v2"}


# ---------------------------------------------------------------------------
# build_variant_graph
# ---------------------------------------------------------------------------


def test_build_variant_graph_derived_from_chain(bundles):
    """DERIVED_FROM runs v1 → v2 → v3 along the composed VARIANT nodes."""
    variant_set = build_variant_set(
        [bundles["v1"], bundles["v2"], bundles["v3"]]
    )[0]
    graph = build_variant_graph(variant_set)

    v1, v2, v3 = (_variant_node(graph, i) for i in (0, 1, 2))
    assert graph.has_edge(v1, v2)
    assert graph.edges[v1, v2]["type"] == "DERIVED_FROM"
    assert graph.has_edge(v2, v3)
    assert graph.edges[v2, v3]["type"] == "DERIVED_FROM"
    # No spurious jump from the root straight to the grandchild.
    assert not graph.has_edge(v1, v3)


def test_build_variant_graph_shares_source_with(bundles):
    """SHARES_SOURCE_WITH links the shared media asset across every member."""
    variant_set = build_variant_set(
        [bundles["v1"], bundles["v2"], bundles["v3"]]
    )[0]
    graph = build_variant_graph(variant_set)

    shares = _edges_of_type(graph, "SHARES_SOURCE_WITH")
    # Three members reference one shared asset ⇒ 3 undirected pairs.
    assert len(shares) == 3
    for u, v in shares:
        assert graph.nodes[u]["type"] == "MEDIA_ASSET"
        assert graph.nodes[v]["type"] == "MEDIA_ASSET"
        assert graph.nodes[u]["entity_id"] == graph.nodes[v]["entity_id"]


def test_build_variant_graph_alternative_of_between_siblings(bundles):
    """ALTERNATIVE_OF joins v2 and its same-ordinal sibling v2_alpha."""
    variant_set = build_variant_set(list(bundles.values()))[0]
    graph = build_variant_graph(variant_set)

    # Members sorted (ordinal, snapshot_id): v1, v2, v2_alpha, v3 ⇒ the two
    # ordinal-1 siblings sit at snapshot_ordinal 1 and 2.
    sib_a, sib_b = _variant_node(graph, 1), _variant_node(graph, 2)
    alt = _edges_of_type(graph, "ALTERNATIVE_OF")
    assert (sib_a, sib_b) in alt or (sib_b, sib_a) in alt
    # A linear pair (root vs grandchild) is never an alternative.
    assert len(alt) == 1


# ---------------------------------------------------------------------------
# variant_diff
# ---------------------------------------------------------------------------


def test_variant_diff_v1_v2_reports_added_track(bundles):
    """v1 → v2 adds exactly one track (the drum kit)."""
    delta = variant_diff(bundles["v1"], bundles["v2"])
    added_tracks = [r for r in delta.added_entities if r.type == "TRACK"]
    assert [r.id for r in added_tracks] == ["demo:track-drums"]
    # No track was removed, and no send changed on this step.
    assert not delta.removed_entities
    assert not delta.added_sends


def test_variant_diff_v2_v3_reports_added_send(bundles):
    """v2 → v3 adds the vocal → reverb send."""
    delta = variant_diff(bundles["v2"], bundles["v3"])
    assert len(delta.added_sends) == 1
    send = delta.added_sends[0]
    assert send.type == "CHANNEL_SENDS_TO"
    assert "Reverb Return" in send.label


def test_variant_diff_v2_v3_reports_parameter_change(bundles):
    """v2 → v3 also bumps the vocal EQ Gain, read back with role + owner."""
    delta = variant_diff(bundles["v2"], bundles["v3"])
    assert len(delta.parameter_changes) == 1
    change = delta.parameter_changes[0]
    assert change.role == "GAIN"
    assert change.before_value == 0.5
    assert change.after_value == 0.7
    assert change.processor_id == "demo:proc-eq"
    assert change.channel_id == "demo:track-vox:channel"
